import { Context } from "./Context";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create visitors book",
  description: "Generated by jieun vin",
};

export default async function RootLayout({ children }) {
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', { next: { revalidate: 0 } });
  const result = await res.json();

  return (
    <html>
      <body>
        <main>
          <h1 className='main_title'>
          <Link href="/">방명록</Link>
        </h1>

        <div className='list'>
          <ol>
          {result.map(item => {
            return<Link key={item.id} href={`/read/${item.id}`}><li>{item.title}</li></Link>;
          })}
        </ol>
        </div>
        
        {children}

        <div className='main_list'>
          <ul>
          <li><Link href='/create'>방명록 올리기</Link></li>
          <Context />
        </ul>
        </div>
        
        </main>
      </body>
    </html>
  );
}


